// Parity + contract tests for the AIEDS v1 reference library.
//
// The PARITY FIXTURE below was generated by executing the shipped rand0m.ai
// app implementation (lib/models/aieds/aieds_disclosure.dart,
// AiedsDisclosure.fromResponse) on 2026-07-09 with the same inputs — the
// reference library must reproduce those numbers exactly, so the app and the
// standard agree to the number.
import assert from "node:assert/strict";
import test from "node:test";

import {
  AIEDS_VERSION,
  MODELED_GRID_INTENSITY_GRAMS_PER_KWH,
  disclosureFromResponse,
  treeTimeLabel,
  treeTimeMinutesFor,
} from "../index.js";

const EPS = 1e-12;
const close = (a: number, b: number) =>
  assert.ok(Math.abs(a - b) <= EPS * Math.max(1, Math.abs(b)), `${a} !== ${b}`);

test("parity fixture: matches the app's AiedsDisclosure.fromResponse output", () => {
  const d = disclosureFromResponse({
    provider: "GoogleAI",
    model: "gemini-test",
    latencyMs: 1234,
    inputTokens: 321,
    outputTokens: 654,
    costUsd: 0.0042,
    carbonGrams: 0.5,
  });
  // Values produced by the Dart implementation (see header).
  close(d.energyWh, 1.1655011655011656);
  close(d.carbonGrams, 0.5);
  close(d.treeTimeMinutes, 11.945454545454545);
  assert.equal(d.treeTimeLabel, "11.9 min");
  close(d.phoneCharges, 0.09712509712509713);
  close(d.ledBulbHours, 0.11655011655011656);
  close(d.laptopMinutes, 1.3986013986013988);
  close(d.drivingMeters, 2.941176470588235);
  assert.equal(d.totalTokens, 975);
  assert.equal(d.confidence, "estimated");
  assert.equal(d.aiedsVersion, AIEDS_VERSION);
});

test("parity fixture: negative carbon clamps to zero everywhere", () => {
  const d = disclosureFromResponse({ provider: "x", carbonGrams: -3 });
  assert.equal(d.energyWh, 0);
  assert.equal(d.treeTimeMinutes, 0);
  assert.equal(d.treeTimeLabel, "0 min");
  assert.equal(d.carbonGrams, 0);
});

test("parity fixture: large carbon renders the hours label", () => {
  const d = disclosureFromResponse({ provider: "x", carbonGrams: 3000 });
  close(d.treeTimeMinutes, 71672.72727272726);
  assert.equal(d.treeTimeLabel, "1194.5 hrs");
});

test("tree-time formula and label edge cases", () => {
  assert.equal(treeTimeMinutesFor(0), 0);
  assert.equal(treeTimeMinutesFor(-1), 0);
  // 22 kg = one Mature Reference Tree for one year = 525600 minutes.
  close(treeTimeMinutesFor(22000), 525600);
  assert.equal(treeTimeLabel(0.5), "<1 min");
  assert.equal(treeTimeLabel(59.94), "59.9 min");
  assert.equal(treeTimeLabel(60), "1.0 hrs");
});

test("energy inversion uses the pinned app-surface grid intensity (429)", () => {
  assert.equal(MODELED_GRID_INTENSITY_GRAMS_PER_KWH, 429);
  const d = disclosureFromResponse({ provider: "x", carbonGrams: 429 });
  close(d.energyWh, 1000); // 429 g at 429 g/kWh == exactly 1 kWh == 1000 Wh
});

test("defaults: missing optionals are zeroed, disclosure copy attached", () => {
  const d = disclosureFromResponse({ provider: "OpenAI" });
  assert.equal(d.inputTokens, 0);
  assert.equal(d.outputTokens, 0);
  assert.equal(d.costUsd, 0);
  assert.equal(d.energyWh, 0);
  assert.equal(d.notes.length, 3);
  assert.match(d.notes[0], /AIEDS v1/);
});
